mipengine/mip2-extensions

components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-2-1.html, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
#201 
**1、升级点** （
小说阅读器  修复目录页点击章节后边空白处不跳转
）
**2、影响范围** （无）
小说阅读器  修复目录页点击章节后边空白处不跳转
**5、自测机型和浏览器**
=> 小说阅读器  修复目录页点击章节后边空白处不跳转

.travis.yml
travis 构建 npm install 安装依赖偶尔会超时，增加 retry 方法
对组件无影响，免测
=> fix travis npm install timeout issue

components/mip-form/mip-form.less, components/mip-inservice-pay/mip-inservice-pay.vue, components/mip-novel-video/mip-novel-video.vue, components/mip-toast/README.md, components/mip-toast/mip-toast.vue
在sf的ios下，支持提示框居中
无
**5、自测机型和浏览器**
=> 【申请免测】 修复mip-toast在ios的sf下不居中问题

components/mip-mathml/README.md, components/mip-mathml/example/mip-mathml.html, components/mip-mathml/mip-mathml.vue
**1、升级点** 
mip-mathml 组件，使用 mathml 语言编写数学公式
为了避免 mathjax.js 对主页面的影响，并且需要对加载速度有要求，使用 iframe 渲染 Mathml，大体思路：
1. 创建 iframe，cdn 加载 mathml 核心库 mathjax
2. 把字符渲染成数学公式
3. 渲染完后设置 iframe 宽高
**2、影响范围** 
无
-  [x] 常见数学公式
-  [x] 内敛方式的数学公式
**5、自测机型和浏览器**
=> feat: 完成 mip-mathml 组件

components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
bug  线上目录页监控发送了common异常日志
情况：章节目录监控了common异常日志，但目录页common未请求，
原因：测试时未测目录章节部分，而目录页加载了小说阅读器组件，小说阅读器组件发送common异常
解决：有common请求时才监控异常，判断是否有mip-custom组件再 监控异常
**5、自测机型和浏览器**
=>  fix: 修复线上目录页不应监控common异常日志

package.json, tools/site.js
组件的 example 目录下如果包含子目录，构建生成预览页面时，不能递归拷贝，会出现预览失败的情况。
对组件无影响
**5、自测机型和浏览器**
=> 修复: 构建时的示例预览页不支持子目录的问题

components/mip-nav-slidedown/README.md, components/mip-nav-slidedown/mip-nav-slidedown.js
#402 
修复 mip-nav-slidedown 下拉列表的按钮无法点击的 bug
线上 v2 的 mip-nav-sildedown 组件
1. 组件 example 点击关闭按钮能正常收起下来菜单
**5、自测机型和浏览器**
=> fix：修复 mip-nav-slidedown 下拉列表的按钮无法点击的 bug

components/mip-showmore/mip-showmore.less
[462](https://github.com/mipengine/mip2-extensions/issues/462)
IOS 手百合作页折叠组件文字透出
IOS 手百医疗合作页
不同资源方的合作页折叠效果
不同手机和浏览器合作页折叠效果
**5、自测机型和浏览器**
=> fix:修复IOS上折叠组件下面文字透出的问题

components/mip-vd-tabs/mip-vd-tabs.js, components/mip-vd-tabs/tab.js
Android 4.4 小米原生浏览器，剧集展开时箭头样式不正确。
原因：该浏览器不支持 transform: scaleY(-1) 属性，组件原来的逻辑使用 js 设置样式的时候，书写有误。
**5、自测机型和浏览器**
=> fix：mip-vd-tabs 个别浏览器展现有误

components/mip-accordion/mip-accordion.js
#415 
1. 修复 mip 组件嵌套会被 accordion 影响到的问题
2. 修复 accordion 在 section 嵌套的情况下子 section 展开高度无法撑开父 section 的bug
mip-accordion
1. mip-accordion 组件嵌套时相互之间不受影响
2. section 嵌套时子 section 能正常展开父 section
**5、自测机型和浏览器**
=> 修复 accordion MIP 组件嵌套 & section 嵌套 bug

components/mip-scrollbox/mip-scrollbox.js
#415 
1. 使用兼容性方法来处理样式注入
1. mip-scrollbox
**5、自测机型和浏览器**
=> 修复 mip-scrollbox 在 iOS 9 下面样式不对的 bug

components/mip-scrollbox/mip-scrollbox.js
#494 
Object.assign 改成 util.fn.extend
mip-scrollbox
**5、自测机型和浏览器**
=> 修复 IOS9 下面 mip-scrollbox 样式不对的 bug

components/mip-shell-xiaoshuo/ad/strategyCompute.js, components/mip-shell-xiaoshuo/ad/strategyControl.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
#531 
新增机制，对线上无影响
和后端联调通过
需要配合新的 mip-custom 一起测试联调
主要测试点：
1、每个页面根据 schema 算出需要出的广告，并且页面正常展现广告，下面分别是 cache 和 nocache 的典型 schema
2、根据上图可知：现在 cache 机制下只有 page 页面类型，其他页面类型（包括详情页）都在 nocache 机制下进行，schema 的计算方式和原来一样，只是广告数据存储的字段不一样了，cache 机制的广告在 ads 字段，nocache 机制的广告在 nocacheads，如下图：
3、cache 机制和 nocache 机制互不影响，也就是说 page 和 page_8 或chapterEnd 可以共存，这几种页面类型的广告可以叠加显示
4、在后台不上线的情况下（即直接使用现在线上数据的情况），上线顺序相关的测试：1）只更新shell-xiaoshuo，不更新mip-custom，线上应该正常；2）二者都更新，线上也应该正常。
**5、自测机型和浏览器**
=> 小说 nocache 机制完成

components/mip-shell-xiaoshuo/ad/strategyControl.js
#551 
修复page_8不展现凤巢广告的问题
代理测试，线上 page_8 可以正常出凤巢广告，但是品专广告目前还没有数据，不能展现。
**5、自测机型和浏览器**
=> 没有品专广告数据时返回error，变更参数使其暂时正常

components/mip-audio/mip-audio.less
修复 `<mip-audio>` 在 iOS 8 下无法显示播放按钮的 bug
所有使用 `<mip-audio>` 的页面
**5、自测机型和浏览器**
=> 修复 ios8 下，播放按钮无法显示的 bug

components/mip-shell-xiaoshuo/common/log.js
#584
修复小说MIP从详情页进入内页时不打adShow日志的问题
从MIP详情页进入广告页
从详情页进入广告页，打开 Network，能够看到有 adShow 的 tc 日志
**5、自测机型和浏览器**
=> 修复小说MIP从详情页进入内页时不打adShow日志的问题

components/mip-map/mip-map.js
https://github.com/mipengine/mip2/issues/576
1. 修改 mip-map 的挂载方式由 defineProperty 改成直接赋值，避免沙盒变量增减造成的 redefine 错误
1. mip-map
2. 线上蓝犀牛
1. mip-map 正常工作
2. MIP.sandbox.BMap 正常访问
**5、自测机型和浏览器**
=> [fix] 修改 mip-map 将 BMap 挂载到沙盒对象上的方法

components/mip-city-selection/mip-city-selection.js, components/mip-confirm/example/mip-confirm1.html, components/mip-confirm/example/mip-confirm2.html, components/mip-confirm/example/mip-test.js, components/mip-confirm/mip-confirm.js, components/mip-toast/README.md, components/mip-toast/example/mip-toast.html, components/mip-toast/example/mip-toast1.html, components/mip-toast/example/mip-toast2.html, components/mip-toast/example/mip-toast3.html, components/mip-toast/mip-toast.js
#615 
bugfix：mip-fixed 在 iOS + iframe 环境下会被移动到 body 之外导致  DOM 操作报错
mip-toast, mip-confirm, mip-city-selection
**5、自测机型和浏览器**
=> fixed: 修复 mip-fixed 在 iOS + iframe 下的问题 #615

components/mip-anim/README.md, components/mip-anim/example/mip-anim.html, components/mip-selector/README.md
修复 mip-selector 和 mip-anim 组件 README 文件里不可见的 img
影响官方网站组件的演示效果，修复之前有几个图片加载不到，修复后可见
**5、自测机型和浏览器**
=> fix: 修复 mip-selector 和 mip-anim 组件 README 文件里不可见的 img

components/mip-custom/common/url.js
#663 
mip-custom 在百度域和mipcdn外加参数noshell
所有mip小说页面，广告正常展现
mip小说传的一个参数 noshell  判断加不加这个参数的方法改了下 其他逻辑没有改动
代理线上小说测试，广告展现正常
**5、自测机型和浏览器**
=> 判断当前域名或referrer，从而加个参数noshell

.travis.yml
用于组件截图测试的 percy 服务目前大概率误报，暂时从 travis 集成服务中移除。
**5、自测机型和浏览器**
=> remove percy from travis

components/mip-action-macro/README.md, components/mip-action-macro/example/index.html, components/mip-action-macro/index.less, components/mip-action-macro/mip-action-macro.js
https://github.com/mipengine/mip2/issues/679
依赖 mip2 改动暴露 MIP.util.parse 方法：
https://github.com/mipengine/mip2/pull/698
新增 mip-action-macro
1. 在使用 on 表达式的时候可以通过 mip-action-macro 实现行为复用；
2. 增加 condition，使得行为在执行前可以先通过分支判断来决定是否触发行为；
3. 支持行为传参，通过 [id].execute(arg1=xxx,arg2=xxx) 的方式传入 mip-action-macro 当中，并可以在 condition 表达式和 on 表达式里面通过 event.arg1 event.arg2 访问到参数。
无
**5、自测机型和浏览器**
=> feat: 新增 mip-action-macro

components/mip-autocomplete/README.md, components/mip-autocomplete/example/mip-autocomplete.html, components/mip-autocomplete/mip-autocomplete.ts
使 template 下可以只用 menu 等块级元素
暂无影响
**5、自测机型和浏览器**
=> fix: 使 template 下可以用 section 等块级元素，已 id 标识
