mipengine/mip2-extensions

components/mip-script/mip-script.vue
=> Mip script

components/mip-link/example/mip-link.html
feat：add mip2-extensions mip-link demo跳转到官网首页
=> feat：add mip2-extensions mip-link demo跳转到官网首页

.eslintrc
=> 增加 no-var 规则

components/mip-shell-inservice/example/index.html, components/mip-shell-inservice/example/mip-shell-inservice-2.html, components/mip-shell-inservice/example/mip-shell-inservice-3.html, components/mip-shell-inservice/example/mip-shell-inservice.html, components/mip-shell-inservice/mip-shell-inservice.js, components/mip-shell-inservice/mip-shell-inservice.less, components/mip-shell-inservice/mip-shell-inservice.md
=> 极速服务组件更改bug

.travis.yml
添加 branch 配置，只对 master 分支进行持续集成
参考：
[https://docs.travis-ci.com/user/web-ui/#Build-pushed-branches](https://docs.travis-ci.com/user/web-ui/#Build-pushed-branches)
[https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches](https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches)
=> add branch conf in .travis.yml

components/mip-script/mip-script.vue
=> Mip script 调整 slot 用法

components/mip-novel-video/mip-novel-video.vue, components/mip-novel-video/video-detector.js
=> test：mip-novel-video 添加品专视频广告 添加测试console

components/mip-novel-video/mip-novel-video.vue
=> fix：mip-novel-video 修改播放结束自动关闭的逻辑

components/mip-novel-video/mip-novel-video.vue
修改timeExpired并且修改清除为30秒清除，为showcase准备
=> fix: 修改timeExpired

components/mip-novel-video/mip-novel-video.vue
=> fix: 修改判断是否百度域的bug

components/mip-novel-video/mip-novel-video.vue
=> fix: 修改SF判断逻辑

components/mip-novel-video/example/mipx-xiaoshuo-1.html, components/mip-novel-video/example/mipx-xiaoshuo-2.html, components/mip-novel-video/example/mipx-xiaoshuo-3.html, components/mip-novel-video/mip-novel-video.vue, components/mip-novel-video/video-detector.js
=> fix: 禁止UC视频，15秒自动关闭

components/mip-tabs/README.md, components/mip-tabs/example/mip-tabs.html, components/mip-tabs/mip-tabs-item.vue, components/mip-tabs/mip-tabs.vue
=> feat:添加mip-tabs组件

components/mip-shell-xiaoshuo/header.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
=> Noval shell

components/mip-inservice-pay/mip-inservice-pay.md, components/mip-inservice-pay/mip-inservice-pay.vue, components/mip-shell-inservice/example/index.html, components/mip-shell-inservice/example/mip-shell-inservice-2.html, components/mip-shell-inservice/example/mip-shell-inservice-3.html, components/mip-shell-inservice/example/mip-shell-inservice.html, components/mip-shell-inservice/lib/MoreAction.js, components/mip-shell-inservice/lib/ProcessConfig.js, components/mip-shell-inservice/lib/scrollBoundary.js, components/mip-shell-inservice/mip-shell-inservice.js
1. shell-inservice 组件进行代码优化，以及bugfix
2.支付组件 修复 某些机型 props数据 绑定不同步问题
=> fix支付组件props数据，优化inservice shell代码

README.md
=> fix: readme 链接

components/mip-shell-xiaoshuo/ad/strategy.js, components/mip-shell-xiaoshuo/common/events.js, components/mip-shell-xiaoshuo/common/state.js, components/mip-shell-xiaoshuo/common/util.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=> fix: 修改语法规范2

components/mip-shell-inservice/lib/MoreAction.js
shell 在sf环境跳转关于页面时 增加nocache参数
打点日志中增加click_token
sf环境下跳转关于页面
功能已自测
**5、自测机型和浏览器**
=> 增加loadiframe nocache参数

components/mip-shell-xiaoshuo/ad/strategy.js, components/mip-shell-xiaoshuo/common/events.js
=> feat: 兼容如果小说shell优先加载custom无法监听请求事件的问题

components/mip-shell-xiaoshuo/ad/strategy.js
=> feat: 定制化组件升级添加发小说shellready事件3

components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-1.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-2.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-3.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-2-1.html, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.md
=> mip-shell-xiaoshuo feat: 新增小说阅读器目录页

components/mip-shell-xiaoshuo/ad/strategy.js
=> feat: 小说shell添加判断是否root的问题以方便广告的请求

components/mip-stats-tianrun/README.md, components/mip-stats-tianrun/example/mip-stats-tianrun.html, components/mip-stats-tianrun/mip-stats-tianrun.js
**提交pr时需要关联issue，请大家遵守** 
issue:  #170 
迁移至2.0
新迁移，线上无引用
- 脚本正常加载
**5、自测机型和浏览器**
=> add/mip-stats-tianrun 添加天润统计组件【免测】

components/mip-inservice-login/mip-inservice-login.md, components/mip-inservice-login/mip-inservice-login.vue
=> 增加返回页面时的登录状态查询

.stylelintrc, components/mip-anim/mip-anim.vue, components/mip-appdl/mip-appdl.vue, components/mip-city-selection/mip-city-selection.vue, components/mip-confirm/mip-confirm.vue, components/mip-html-os/mip-html-os.vue, components/mip-inservice-login/mip-inservice-login.md, components/mip-inservice-pay/mip-inservice-pay.vue, components/mip-link/mip-link.vue, components/mip-map/mip-map.vue, components/mip-novel-video/mip-novel-video.vue, components/mip-range/mip-range.vue, components/mip-shell-inservice/mip-shell-inservice.less, components/mip-shell-xiaoshuo/common/util.js, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less, components/mip-tabs/mip-tabs-item.vue, components/mip-tabs/mip-tabs.vue, components/mip-toast/mip-toast.vue, package.json
##**提交pr时需要关联issue，请大家遵守**
#206 
1. 增加 stylelint + stylelint-config-standard
2. pre-commit 阶段增加 css/less/vue 的样式校验
3. 命令行增加 lint:style / fix:style 命令，分别对应样式的手动校验规范和自动修复
1. 开发阶段的开发体验
2. 组件上线前校验
**5、自测机型和浏览器**
=> 增加 stylelint 代码校验，并格式化现有代码

components/mip-audio/README.md, components/mip-audio/example/mip-audio.html, components/mip-audio/mip-audio.js, components/mip-audio/mip-audio.less
#197 
无
无
原组件介绍：https://www.mipengine.org/examples/mip-extensions/mip-audio.html
手百已覆盖，
安卓，ios11
**5、自测机型和浏览器**
=> fix:迁移mip-audio

components/mip-inservice-login/mip-inservice-login.md, components/mip-inservice-login/mip-inservice-login.vue
=> 【免测】Update/readme2

components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-4-1.html, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
issue : #244 
1、目录页展开时，向左滑收起目录；
2、设置页展开时，向上、下滑收起设置。
3、目录修窄，遮盖层目前不加
4、去掉滚动条
5、新增测试用例，无book字段，mipx-xiaoshuo-4-1.html
无
1、目录页展开时，向左滑收起目录；
2、设置页展开时，向上、下滑收起设置。
3、目录修窄，遮盖层目前不加
4、去掉滚动条
5、新增测试用例，无book字段，mipx-xiaoshuo-4-1.html
**5、自测机型和浏览器**
=> feat:  小说新功能左滑目录页消失，上下滑设置页消失，增加无book字段测试用例

components/mip-shell-xiaoshuo/ad/const.js, components/mip-shell-xiaoshuo/ad/strategy.js, components/mip-shell-xiaoshuo/common/state.js, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-1.html
#256 
在common请求的中novelData字段中添加originalUrl
暂无
chrome，safari
**5、自测机型和浏览器**
=> feat: 断点续读的原始URL的参数的传递 #256

components/mip-nav-slidedown/README.md, components/mip-nav-slidedown/example/2.html, components/mip-nav-slidedown/example/3.html, components/mip-nav-slidedown/example/mip-nav-slidedown.html, components/mip-nav-slidedown/mip-nav-slidedown.js, components/mip-nav-slidedown/mip-nav-slidedown.less
=> feat:迁移mip-nav-slidedown

components/mip-shell-xiaoshuo/ad/strategy.js, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-2.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-3.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-2-1.html, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
#256 
添加小说发广告请求时带书名参数
暂无
chrome
**5、自测机型和浏览器**
=> feat: 断点续读的添加书名的参数 #256

components/mip-semi-fixed/README.md, components/mip-semi-fixed/example/mip-semi-fixed.html, components/mip-semi-fixed/mip-semi-fixed.js, components/mip-semi-fixed/mip-semi-fixed.less
#24
按照ES6作出语法修改
mip2-extensions官方组件库
1.测试默认顶部悬浮效果
2.测试距离顶部为固定宽度时的悬浮效果
**5、自测机型和浏览器**
=> feat: mip-semi-fixed组件迁移至2.0 #24

components/mip-shell-xiaoshuo/common/state.js, components/mip-shell-xiaoshuo/common/util.js, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-1-3.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-2-1.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-3-1.html, components/mip-shell-xiaoshuo/example/mipx-xiaoshuo-4-1.html, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
=> fix：修改crid的获取方式

components/mip-shell-xiaoshuo/feature/catalog.js
=> 修复小说异步目录跳转链接bug #268

components/mip-shell-xiaoshuo/feature/catalog.js
=> fix:修复小说异步目录跳转链接bug #268

components/mip-toast/README.md, components/mip-toast/example/mip-toast.html, components/mip-toast/example/mip-toast1.html, components/mip-toast/example/mip-toast2.html, components/mip-toast/example/mip-toast3.html, components/mip-toast/mip-toast.vue
#274 
文字部分可动态传入
无
ios Chrome Android
**5、自测机型和浏览器**
=> 【申请免测】feat : 升级mip-toast组件，动态传提示文字

components/mip-list/README.md, components/mip-list/example/mip-list.html, components/mip-list/mip-list.js
#23 
按照es6作出语法修改
mip2-extensions官方组件库
1.同步异步获取数据
2.数据渲染
**5、自测机型和浏览器**
=> feat: mip-list迁移2.0

components/mip-shell-xiaoshuo/ad/strategy.js, components/mip-shell-xiaoshuo/common/events.js
#283 
common增加是否第二页的字段
线上添加小说阅读器的页面
1、渲染没有问题；
2、功能OK；
3、common请求参数没问题；
**5、自测机型和浏览器**
=> feat: common增加是否第二页的字段 #283

components/mip-shell-xiaoshuo/ad/strategy.js
#295 
小说阅读器需要增加小说详情页页面，需要增加给后端传的pageType字段
**5、自测机型和浏览器**
=> 【申请免测】 feat: 小说阅读页增加pageType字段

components/mip-shell-xiaoshuo/common/log.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=>  feat: 小说阅读器 添加common请求异常日志

components/mip-tabs/example/mip-tabs.html, components/mip-tabs/mip-tabs.vue
#321 
bug修复
mip-tabs
example中的例子
**5、自测机型和浏览器**
=> 修复 slideTab 无法跳转

components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
=>  fix: 小说阅读器 修复两层iframe情况下小说阅读器页面样式失效问题

components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=>  fix: common异常打点代码被修改

components/mip-shell-xiaoshuo/common/log.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=>  feat: 小说埋点，新增首跳二跳展现和广告展现埋点

components/mip-shell-xiaoshuo/ad/strategyControl.js, components/mip-shell-xiaoshuo/common/events.js, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/feature/footer.js
#342 
核心代码的部分功能异步可能引起组件间通信问题
针对问题进行部分修改，把原先在bindRootEvents中的内容放到bindAllEvents内
chrome
**5、自测机型和浏览器**
=> feat: 小说配合核心部分功能异步

components/mip-shell-xiaoshuo/ad/strategyControl.js
#346 
bugfix一个合并后的赋值
暂无
chrome
**5、自测机型和浏览器**
=> fix: 小说广告合并详情页的bugfix

components/mip-shell-xiaoshuo/feature/footer.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
This reverts commit 798710b67ec61041f36c4d636bf96d76c5a222fa.
回滚小说预渲染逻辑
=> Revert "小说阅读器内部预渲染：翻页关闭工具栏 Feat/xsprerendernew (#351)"

components/mip-audio/mip-audio.js, components/mip-shell-xiaoshuo/feature/footer.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less, components/mip-showmore/mip-showmore.js
This reverts commit f05d271925d3d60bdb2228268c6c3a6e74052a82.
**5、自测机型和浏览器**
=> Revert "#318小说阅读器内部预渲染 (#319)"

components/mip-shell-xiaoshuo/common/log.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=> fix: 修改广告展现偶现不打点情况

components/mip-shell-xiaoshuo/ad/strategyCompute.js, components/mip-shell-xiaoshuo/ad/strategyControl.js, components/mip-shell-xiaoshuo/common/log.js, components/mip-shell-xiaoshuo/common/util.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
#360 
小说添加小说实例ID和frsrcid和广告合并的一个策略bugfix
线上使用广告合并的小流量
chrome
**5、自测机型和浏览器**
=> feat：小说添加小说实例ID和frsrcid #360

components/mip-shell-xiaoshuo/feature/footer.js, components/mip-shell-xiaoshuo/feature/prerender.js, components/mip-shell-xiaoshuo/feature/setting.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
=> 小说内部预渲染 - 单独抽离文件Feat/prerendernew

components/mip-env/mip-env.js
#364 
修改了对百度APP的判断
线上小说纵横引用了该组件的页面
chrome
**5、自测机型和浏览器**
=> fix: mip-env下手百的判断

components/mip-shell-xiaoshuo/common/flag.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
(#369)
修复雪中悍刀行源站报错问题
雪中悍刀行源站
**5、自测机型和浏览器**
=> 修复雪中悍刀行源站报错问题

components/mip-shell-xiaoshuo/feature/prerender.js
=> fix：预渲染不修改翻页按钮链接

components/mip-env/README.md, components/mip-env/example/mip-env.html, components/mip-env/mip-env.js
#364 
由于结果页内SF对fixed元素的特殊处理，需要添加id来进行标识
暂无
chrome
**5、自测机型和浏览器**
=> fix: mip-env在结果页下对fixed元素的处理

components/mip-shell-xiaoshuo/ad/strategyCompute.js
#374 
bugfix，修改循环终止逻辑
线上小说使用了广告合并的页面
chrome
**5、自测机型和浏览器**
=> fix: 小说详情页广告的展现bug

components/mip-appdl/mip-appdl.vue
#377
修复该组件使用了不存在的 util 导致报错，详情见 issue
该组件正常展现
测试环境及build 编译产物均显示正常
**5、自测机型和浏览器**
=> fix：修改 mip-appdl 组件使用 jsonParse

components/mip-shell-xiaoshuo/ad/strategyCompute.js
=> fix:修改AD_DATA_CACHE为600000

.eslintrc, package.json
增加 babel-eslint
无
npm run lint 能正常跑
**5、自测机型和浏览器**
=> 【免测】eslint 增加对 dynamic import 的语法检测支持

components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
=> feat：增加重新加载按钮以及倒序展现

components/mip-image-slider/README.md
=> 更新 mip-image-slider readme 文档

components/mip-env/README.md, components/mip-env/example/mip-env.html, components/mip-env/mip-env.js
#395 
增加baidubrowser
mip-env组件
chrome, baidubrowser UA 
**5、自测机型和浏览器**
=> feat: 新增ua判定，增加百度浏览器

components/mip-accordion/mip-accordion.js, components/mip-app-banner/mip-app-banner.js, components/mip-audio/mip-audio.js, components/mip-lightbox/mip-lightbox.js, components/mip-shell-xiaoshuo/common/log.js, components/mip-showmore/mip-showmore.js
**1、升级点** 参考 https://github.com/mipengine/mip2/issues/448
**2、影响范围** 
- 所有使用 mip-audio 的站点
- 同 https://github.com/mipengine/mip2/pull/454
**5、自测机型和浏览器**
=> fix: Controls audio when page is switching

components/mip-env/README.md, components/mip-env/example/mip-env.html, components/mip-env/mip-env.js
#398 
添加微信ua识别，去除对dp的iframe限制
mip-env
chrome wechatUA ,  phone wechat 
**5、自测机型和浏览器**
=> feat: 添加微信ua识别，去除对dp的iframe限制

components/mip-env/README.md, components/mip-env/example/mip-env.html, components/mip-env/mip-env.js
#398 
添加微信ua识别，去除对dp的iframe限制 
mip-env组件
chorme wechat ua, ios wechat
**5、自测机型和浏览器**
=> feat：添加微信ua识别，去除对dp的iframe限制 

components/mip-install-serviceworker/README.md, components/mip-install-serviceworker/example/install.html, components/mip-install-serviceworker/example/mip-install-serviceworker.html, components/mip-install-serviceworker/example/shell.html, components/mip-install-serviceworker/example/sw.js, components/mip-install-serviceworker/install-url-rewiter.js, components/mip-install-serviceworker/mip-install-serviceworker.js, components/mip-install-serviceworker/util.js
#415 
新增 mip-install-serviceworker 组件
线上暂时无影响，该组件无站点使用
**5、自测机型和浏览器**
=> feat: 迁移 mip-install-serviceworker

components/mip-install-serviceworker/README.md
=> 修改 Markdown 换行问题

components/mip-form/README.md, components/mip-form/example/mip-form.html, components/mip-form/mip-form-fn.js, components/mip-form/mip-form.js
#415 迁移 mip-form 组件
使用 mip-form 组件的站点
**5、自测机型和浏览器**
=> feat: 迁移 mip-form

components/mip-widget-full-height/README.md, components/mip-widget-full-height/example/index.html, components/mip-widget-full-height/mip-widget-full-height.js
=> feat: 迁移 mip-widget-full-height

components/mip-filter/README.md, components/mip-filter/example/mip-filter.html, components/mip-filter/mip-filter.js
#415 迁移 mip-filter 组件
使用 mip-filter 的站点
**5、自测机型和浏览器**
=> feat: 迁移 mip-filter

components/mip-stats-baidu/README.md, components/mip-stats-baidu/example/mip-stats-baidu-attr.html, components/mip-stats-baidu/example/mip-stats-baidu-json.html, components/mip-stats-baidu/mip-stats-baidu.js
=> feat: mip-stats-baidu 组件迁移

components/mip-semi-fixed/README.md, components/mip-semi-fixed/example/mip-semi-fixed.html, components/mip-semi-fixed/mip-semi-fixed.js
=> 更新 mip-semi-fixed

components/mip-history/README.md, components/mip-history/example/mip-history.html, components/mip-history/mip-history.js, components/mip-history/mip-history.less
#415 迁移 mip-history 组件
使用 mip-history 组件的站点
**5、自测机型和浏览器**
=> feat: 迁移 mip-history

components/mip-analytics/README.md, components/mip-analytics/example/mip-analytics.html, components/mip-analytics/mip-analytics.js
=> feat: mip-analytics 组件迁移

components/mip-stats-cnzz/README.md, components/mip-stats-cnzz/example/index.html, components/mip-stats-cnzz/mip-stats-cnzz.js
=> feat: mip-stats-cnzz 组件迁移

components/mip-login-done/README.md, components/mip-login-done/example/mip-login-done.html, components/mip-login-done/mip-login-done.html, components/mip-login-done/mip-login-done.js
https://github.com/mipengine/mip2-extensions/issues/415
**5、自测机型和浏览器**
=> feat: 迁移 mip-login-done

components/mip-group-selection/README.md, components/mip-group-selection/example/mip-group-selection1.html, components/mip-group-selection/example/mip-group-selection2.html, components/mip-group-selection/example/mip-group-selection3.html, components/mip-group-selection/mip-group-selection.js, components/mip-group-selection/mip-group-selection.less
#415 
迁移 mip1 的 mip-group-selection 到 mip2
查了下该组件没有站点在使用，而且原组件文档较多错误，已修复
**5、自测机型和浏览器**
=> feat: 迁移 mip-group-selection

components/mip-experiment/example/mip-experiment-4.html, components/mip-experiment/example/mip-experiment-6.html
更新 mip-experiment example 依赖组件的路径为相对路径
**5、自测机型和浏览器**
=> update mip-experiment examples

components/mip-experiment/example/mip-experiment.html
更新 mip-experiment example 
**5、自测机型和浏览器**
=> update mip-experiment example

components/mip-vd-tabs/tab.js
#415 
移除代码中的 `let me = this` 写法
**5、自测机型和浏览器**
=> fix mip-vd-tabs : no assign this

components/mip-list/example/data-has-more.js, components/mip-list/example/data.js
无
修复不支持 let 机器上 example 报错的bug
**5、自测机型和浏览器**
=> 修复不支持 let 机器上 example 报错的bug

components/mip-audio/mip-audio.js, components/mip-semi-fixed/example/mip-semi-fixed.html, components/mip-semi-fixed/mip-semi-fixed.js
1. 修复 mip-audio 在安卓手百下播放按钮显示状态不正确的问题
2. 修复 mip-semi-fixed 在 iframe 下显示不正常的问题
**5、自测机型和浏览器**
=> fix mip-audio and mip-experiment

tools/site.js
=>  修复生成 sf 示例时，所用脚本的兼容性问题

components/mip-list/example/data-has-more.js, components/mip-list/example/data.js, components/mip-showmore/mip-showmore.js
#415 
修复嵌套 showmore 的 init 顺序问题
**5、自测机型和浏览器**
=> 修复嵌套 showmore 的 init 顺序问题

components/mip-ad/example/mip-ad-ssp-fixed.html, components/mip-ad/example/mip-ad-ssp-inline.html, components/mip-ad/mip-ad-baidu.js, components/mip-ad/mip-ad-qwang.js, components/mip-ad/mip-ad-ssp.js, components/mip-ad/mip-ad.js, components/mip-ad/mip-baidu-wm-ext.js, components/mip-ad/mip-baidu-wm-ext.md
#415 
修复 mip-ad 一些问题
**5、自测机型和浏览器**
=> 修复迁移 mip-ad 的 bug

components/mip-ad/mip-ad.js
=> fix 修复mip-embed 注册的问题

components/mip-ad/example/mip-ad-baidu.html, components/mip-ad/example/mip-ad-baidussp.html, components/mip-ad/example/mip-ad-comm.html, components/mip-ad/example/mip-ad-qwang.html, components/mip-ad/example/mip-ad-ssp-fixed.html, components/mip-ad/example/mip-ad-ssp-inline.html, components/mip-ad/example/mip-baidu-wm-ext.html, components/mip-analytics/example/mip-analytics.html, components/mip-stats-baidu/example/mip-stats-baidu-attr.html, components/mip-stats-baidu/example/mip-stats-baidu-json.html, components/mip-stats-baidu/mip-stats-baidu.js, components/mip-stats-cnzz/example/index.html, components/mip-stats-cnzz/mip-stats-cnzz.js, components/mip-stats-tianrun/example/mip-stats-tianrun.html
=> update stats example

components/mip-group-selection/mip-group-selection.less
修复 mip-group-selection css
**5、自测机型和浏览器**
=> fix mip-group-selection css

components/mip-showmore/mip-showmore.js, package.json
#415 
修复 showmore 在 MIP2 中的错误
**5、自测机型和浏览器**
=> 修复 showmore 在 MIP2 中的错误

components/mip-install-serviceworker/example/mip-install-serviceworker.html, components/mip-install-serviceworker/mip-install-serviceworker.js
#523
* 将在 `constructor` 里的 `getAttribute` 和 `hasAttribute` 的操作移动到 `connectedCallback`
使用了 `mip-install-serviceworker` 组件的页面
**5、自测机型和浏览器**
=> 修复 constructor 里调用 getAttribute 引起的问题 #523

components/mip-anim/mip-anim.js, components/mip-appdl/mip-appdl.js, components/mip-audio/example/mip-audio.html, components/mip-audio/mip-audio.js, components/mip-audio/mip-audio.less, components/mip-experiment/mip-experiment.js, components/mip-fastclick/example/index.html, components/mip-fastclick/mip-fastclick.js, components/mip-font/mip-font-loader.js, components/mip-font/mip-font.js, components/mip-gototop/mip-gototop.js, components/mip-image-slider/mip-image-slider.js, components/mip-map/mip-map.js, components/mip-toggle/mip-toggle.js
#523 
修改组件调用 `getAttribute` 的地方
**5、自测机型和浏览器**
=> fix issue #523

components/mip-experiment/mip-experiment.js
#523
1. 将获取元素属性等操作移到 `connectedCallback`
**5、自测机型和浏览器**
=> [免测]fix constructor problem #523

components/mip-ad/mip-ad-baidu.js
#554 
修复 cpro-id 属性不识别的 bug，详见 issue
**5、自测机型和浏览器**
=> [免测]修复 mip-ad:ad-baidu 属性 bug

components/mip-custom/common/data.js, components/mip-custom/common/log.js, components/mip-custom/common/url.js, components/mip-custom/mip-custom.js, components/mip-custom/novel-feature.js
#362 
增加小说相关特性，以及恢复 commonTop 的代码
线上没有使用者，无影响
代理测试了线上的小说，定制化内容正常出现
**5、自测机型和浏览器**
=> mip-custom 增加小说特性

components/mip-custom/mip-custom.js
临时下线 mip-custom 屏蔽 A 区链接的需求
**5、自测机型和浏览器**
=> [bug]临时下线 mip-custom 屏蔽 A 区链接的需求

components/mip-analytics/mip-analytics.js
#567 
修复 mip-analytics 组件获取不到 MIP 性能打点数据的问题
mip-analytics 组件本身
**5、自测机型和浏览器**
=> 【免测】修复 mip-analytics 组件获取不到 MIP 性能打点数据的问题

components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.less
#576 
修复多图横滑模板导致的文字遮挡问题
有多图横滑模板的小说页面
代理测试，安卓手百恢复正常
**5、自测机型和浏览器**
=> 修复小说某个模板遮挡文字的情况

components/mip-map/example/mip-map1.html, components/mip-map/mip-map.js, components/mip-map/mip-map.less
**1、升级点** 
- 支持绘制多个点
- 支持点击绘制的点后弹出搜索框
- 支持由事件传入点的坐标，并弹出搜索框
**2、影响范围** 
- 新增功能，线上应该无影响
- 需求方已自测
**5、自测机型和浏览器**
=> feat: 增强 mip-map 功能

components/mip-shell-xiaoshuo/common/events.js, components/mip-shell-xiaoshuo/feature/catalog.js, components/mip-shell-xiaoshuo/mip-shell-xiaoshuo.js
#588 
修改readPageNum，传递给后端的参数 page_x
品专小说广告展现
console输出当前页的readPageNum，自测通过。
**5、自测机型和浏览器**
=> 修改readPageNum，只有往后翻才算，往前翻不算，从目录进入阅读器则重新开始计算

components/mip-infinitescroll/infinitescroll.js, components/mip-infinitescroll/mip-infinitescroll.js
=> fix infinitescroll eventSpace problem

components/mip-custom/common/data.js
=> mip-custom 增加没有同步到位的字段

components/mip-tabs/mip-tabs.js
=> fix: 修复 tabs 标题颜色变更问题

components/mip-shell-xiaoshuo/ad/strategyControl.js
配合MIP广告改造，增加一些UA字段给后端
所有common请求的novelData字段均增加ua, os, ov, ver 4个字段，不影响其他功能。
分别使用ios和安卓手百访问小说MIP，common请求的novelData中带有新增的字段
使用ios的safari访问，novelData中不含ver字段。
**5、自测机型和浏览器**
=> feat: 配合MIP广告改造，增加一些字段给后端

components/mip-date-display/README.md, components/mip-date-display/example/index.html, components/mip-date-display/mip-date-display.js
新增 mip-date-display 组件
新增 mip-date-display 组件，暂时无人使用，无影响
**5、自测机型和浏览器**
=> feat: 新增 mip-date-display 组件

components/mip-ad/mip-baidu-wm-ext.md
1、升级点
网盟针对反屏蔽接入mip的用户，提供获取token的独立区域。
升级mip接入文档，指导媒体获取mip所需正确token。
2、影响范围
文档面向mip接入反屏蔽广告的媒体，具有指导意义。
=> 'docs:百度联盟广告反屏蔽介绍的修改'

components/mip-env/mip-env.js
- 调整了 mip-env 组件的 log 信息，以前总是会触发 warn 信息
**5、自测机型和浏览器**
=> 【免测】update: 优化 mip-env 组件 log 信息

components/mip-ad/example/mip-ad-baidu.html, components/mip-ad/example/mip-ad-baidussp.html, components/mip-ad/example/mip-ad-comm.html, components/mip-ad/example/mip-ad-qwang.html, components/mip-ad/example/mip-ad-ssp-fixed.html, components/mip-ad/example/mip-ad-ssp-inline.html, components/mip-ad/example/mip-baidu-wm-ext.html, components/mip-sticky-ad/README.md, components/mip-sticky-ad/example/mip-sticky-ad.html, components/mip-sticky-ad/mip-sticky-ad.js, components/mip-sticky-ad/mip-sticky-ad.less
#632 
新增 mip-stick-ad 组件
**5、自测机型和浏览器**
=> feat: 新增 mip-sticky-ad 组件

components/mip-map/mip-map.js, components/mip-user-notification/README.md, components/mip-user-notification/example/data.json, components/mip-user-notification/example/mip-user-notification.html, components/mip-user-notification/mip-user-notification.js, components/mip-user-notification/mip-user-notification.less, components/mip-user-notification/user-notification-maneger.js, components/mip-user-notification/user-notification-ui-maneger.js
新增 mip-user-notification 组件
新组件无人使用，暂无影响
**5、自测机型和浏览器**
=> feat: 新增 mip-user-notification 组件

components/mip-ad/README.md
=> update mip-ad readme

components/mip-custom/common/url.js
提交pr时需要关联issue，请大家遵守
#650
1、升级点 （清晰准确的描述升级的功能点）
结果页fenlei searchFrom order 字段透传至合作页并添加至common请求
2、影响范围 （描述该需求上线会影响什么功能）
合作页common请求
3、自测 checklist
1、从结果页跳转至合作页，common请求中字段是否正常添加，能否正常跳转
4、需要覆盖的场景和case
[ 是 ] 是否覆盖了sf打开mip页
[ 是 ] 是否验证了极速服务mip页面效果
5、自测机型和浏览器
[ 是 ] 是否覆盖了ios系统手机
[ 是 ] 是否覆盖了安卓系统手机
[ 是 ] 是否覆盖了iphone版式浏览器（比如qq、uc、chrome、safari、安卓自带浏览器）
[ 是 ] 是否覆盖了手百
温馨提示：非 mip-extensions 仓库的组件请在组件平台提交，否则一律打回；
=> mod: fenlei searchFrom order 字段透传

components/mip-mustache/sanitizer.js
source 标签需要用到 srcset 属性
**5、自测机型和浏览器**
=> 【免测】fix: mip-mustache 添加合法属性 srcset

components/mip-list/README.md
=> change mip-list md

components/mip-share/README.md, components/mip-share/mip-share.js, components/mip-share/share/share.js, components/mip-share/share/shareConfig.js
#667 
- 新增 mip-share 在微信下的 debug 模式
无
**5、自测机型和浏览器**
=> 【免测】feat: 新增 mip-share 在微信下的 debug 模式

components/mip-toast/mip-toast.js
#671 
修复 show 方法
**5、自测机型和浏览器**
=> 【免测】修复 mip-toast show 参数

components/mip-toast/mip-toast.js
=> fix mip toast bug

components/mip-form/README.md, components/mip-form/example/mip-form.html, components/mip-form/mip-form-fn.js
#676 
新增 clear action，更新文档说明 submit、clear action
新增功能，无影响
**5、自测机型和浏览器**
=> mip-form 更新文档，新增 clear action

components/mip-custom/common/url.js
#691 
统一小说医疗的noshell处理
部分医疗小说页面
代理测试，页面正常展现广告
**5、自测机型和浏览器**
=> 修改noshell的添加方式,保持医疗小说一致

components/mip-list/mip-list.js
#696 
1. 增加 this.src 的初始化
1. 没添加 preload 并且触发 .more 事件的组件
**5、自测机型和浏览器**
=> 增加 this.src 的的初始值

components/mip-list/README.md, components/mip-list/example/mip-list-sync.html, components/mip-list/mip-list.js, components/mip-mustache/README.md
无
1. 更新 mip-list 文档
2. 更新 mip-mustache 文档
无
**5、自测机型和浏览器**
=> [文档更新] 升级 mip-list mip-mustache 的文档

components/mip-list/example/mip-list-compat.html, components/mip-list/mip-list.js
无
1. 修复配置 pnName="xxx" 时拿不到配置的 bug
2. 修复发送请求时拿不到首屏数据的bug
1. mip-list 使用异步请求的页面
**5、自测机型和浏览器**
=> [FIX] 修复 mip-list pn-name 的兼容问题

components/mip-form/README.md, components/mip-script/mip-script.md
=> [文档更新] 更新 mip-script & mip-form 文档

components/mip-form/README.md, components/mip-script/mip-script.md
=> [文档优化] 修复部分线上例子体验

components/mip-accordion/README.md, components/mip-autocomplete/README.md, components/mip-form/README.md, components/mip-list/README.md, components/mip-mustache/README.md, components/mip-script/mip-script.md
=> [文档修改] 修改 mip-form script mustache 等文档

components/mip-action-macro/README.md
无
1. 更新 mip-action-macro 的文档
**5、自测机型和浏览器**
=> [文档更新] 更新 mip-action-macro 的说明文档
